- api/registry/api.py
- api/registry/test/test_passport_submission.py
No longer require signatures for passport scoring. Left placeholder for optional signature enforcement logic.
> feat(api): no longer require signatures for passport scoring

- .github/workflows/ci-staging.yml
Move environment flag after runner, because environment can only be set after runner is set https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#using-an-environment
` The job can access the environment's secrets only after the job is sent to a runner.`
> fix(infra): move environment flag after runner

- .github/workflows/ci-staging.yml
From: https://docs.github.com/en/actions/security-guides/encrypted-secrets
`If a secret with the same name exists at multiple levels, the secret at the lowest level takes precedence. For example, if an organization-level secret has the same name as a repository-level secret, then the repository-level secret takes precedence. Similarly, if an organization, repository, and environment all have a secret with the same name, the environment-level secret takes precedence.`
> fix(infra): create unique variables for staging

- .github/workflows/ci-prod-api.yml
- .github/workflows/ci-review.yml
- .github/workflows/ci-staging.yml
- .github/workflows/ci.yml
- api/Dockerfile
- api/Pipfile
- api/Pipfile.lock
Fixes: https://github.com/gitcoinco/passport-scorer/issues/26
Pipenv was giving me a hard time locally. In order for the python version update to take effect I had to delete the current python environment `pipenv --rm` then run `pipenv update`  to build the updated versions
> feat(api): upgrade to python 3.11

- api/scorer/settings/gitcoin_passport_weights.py
- api/scorer/test/test_create_community_id.py
This fixes: https://github.com/gitcoinco/passport/issues/1128
> fix(scorer): adjusting weights for the beta rounds

- api/registry/api/v1.py
- api/registry/test/test_passport_get_score.py
follow to 1041 to allow external_scorer_id to be passed to endpoint for passport score get and submital
> feat(api): accept external_scorer_id as well as scorer_id

- api/scorer/settings/gitcoin_passport_weights.py
closes https://github.com/gitcoinco/passport/issues/1374
> feat(api): add scoring weight for ZkSyncEra credential

- infra/prod/index.ts
Match the max storage of the primary db instance
> fix(infra): increase max storage on read replica to match main instance

- api/reader/passport_reader.py
- api/reader/tests.py
This fixes: https://github.com/gitcoinco/passport/issues/1543
> 1543 remove backfilling

- .github/workflows/api-ci-review.yml
- .github/workflows/api-promote-prod.yml
- .github/workflows/api-promote-staging.yml
- .github/workflows/ci.yml
These changes will update the workflow files to use Postgres as the database for the api unit tests. We use a feature, `DISTINCT ON`, that can only be used with postgres.
> feat(gh-actions): adds postgres db to github workflow

- infra/lib/scorer/service.ts
- infra/prod/index.ts
- infra/review/index.ts
- infra/staging/index.ts
- things to note: cpu, memory, autoscaling min & max can now be specified in the createScorerECSService
- also cpu & memory, both should take values that are powers of 2
- also adding tags to some of the resources, should help tracking prices
Fixes: https://github.com/gitcoinco/passport/issues/1708
> feat(infra): scale down staging & review

- api/aws_lambdas/submit_passport/submit_passport.py
- api/aws_lambdas/submit_passport/tests/test_submit_passport_lambda.py
Fixes: https://github.com/gitcoinco/passport-scorer/issues/424
> fix(api): handle base64 encoded body in lambda

- infra/prod/index.ts
- infra/staging/index.ts
**Before release store RDS credentials in secrets manager & pass the secret ARN to RDS_SECRET_ARN**
This fixes [Mitigate Database Performance Bottlenecks#448](https://github.com/gitcoinco/passport-scorer/issues/448)
> add RDS secret

- api/aws_lambdas/scorer_api_passport/tests/test_bulk_stamp_lambdas.py
- api/aws_lambdas/scorer_api_passport/tests/test_bulk_stamp_lambdas_v2.py
- api/registry/test/test_command_recalculate_scores.py
- api/scorer/settings/gitcoin_passport_weights.py
- api/scorer/test/conftest.py
- api/scorer_weighted/tests/test_binary_weighted_scorer.py
- load_tests/test_data/config.py
Fixes: https://github.com/gitcoinco/passport/issues/1991
Will need to run `python manage.py recalculate_scores`
Will need to ensure that Magic scorer weights are not rescored in this process. https://github.com/gitcoinco/passport-scorer/blob/99eeda0654212cf77d2aa14697f8c0a4d9443a98/api/registry/management/commands/recalculate_scores.py#L64
> chore(api): remove facebook stamp

- .github/workflows/api-promote-prod.yml
- infra/aws/Pulumi.production.yaml
- infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/2007
> Scorer core vpc prd

- api/data_model/management/commands/scorer_dump_data_eth_model_score.py
- api/data_model/models.py
- api/data_model/test/test_cmd_scorer_dump_data_eth_model_score.py
- adjust Cache model because the table definition has changed)
- adjust scorer_dump_data_eth_model_score command and test
- moved scorer_dump_data_eth_model_score command to data_model app
fixes: https://github.com/gitcoinco/passport/issues/2331
> feat: adjustments in data_model

- api/aws_lambdas/utils.py
- infra/aws/index.ts
- infra/lib/scorer/loadBalancer.ts
This fixes https://github.com/gitcoinco/passport/issues/2228
> update 4xx threshold & timeframe

- infra/lib/scorer/new_service.ts
Fixes: aws:cloudwatch/metricAlarm:MetricAlarm resource 'HTTP-Target-4XX-scorer-api-default' has a problem: Conflicting configuration arguments: "period": conflicts with metric_query. Examine values at 'HTTP-Target-4XX-scorer-api-default.period'.
> fix(infra): remove period config

- api/account/api.py
- api/account/test/test_allow_list.py
fixes: https://github.com/gitcoinco/passport/issues/2604
> chore: add api key

- api/aws_lambdas/passport/analysis_GET.py
- api/aws_lambdas/passport/tests/test_passport_analysis_lambda.py
- api/passport/test/test_analysis.py
- also includes test to check the checksummed address is passed on in the HTTP request querying models
Fixes: https://github.com/gitcoinco/passport/issues/2690
> fix: unquote query string parameter

- api/passport_admin/notification_generators/expired_stamp.py
- api/passport_admin/notification_generators/on_chain_expired.py
- api/passport_admin/tests/test_notifications.py
fixes global on chain and expired notifications
> fix(api): only create deduplication notifications for specific user

- api/aws_lambdas/utils.py
fixes https://github.com/gitcoinco/passport/issues/2717
> feat(api): load all secrets in lambdas

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_production.yml
- .github/workflows/build_and_deploy_review.yml
- .github/workflows/build_and_deploy_staging.yml
- .github/workflows/deploy_generic.yml
- .github/workflows/deploy_production.yml
- .github/workflows/deploy_review.yml
- .github/workflows/deploy_staging.yml
- .github/workflows/interface-ci-production.yml
- .github/workflows/interface-ci-review.yml
- .github/workflows/interface-ci-staging.yml
- .github/workflows/release_and_deploy_production.yml
- .github/workflows/test_generic.yml
Fixes: https://github.com/gitcoinco/passport/issues/2682
> 2627 pulumi 1p secrets 2

- .github/workflows/build_and_deploy_generic.yml
- .github/workflows/build_and_deploy_review.yml
- .github/workflows/test_generic.yml
- api/ceramic_cache/api/v1.py
- api/ceramic_cache/test/test_authenticate_v1.py
- api/scorer/settings/base.py
- infra/aws/index.ts
- infra/aws/verifier.ts
- verifier/src/index.js
Fixes:  https://github.com/passportxyz/passport/issues/2747
> feat: enable the build of the verifier docker image in the workflows

- api/registry/management/commands/process_batch_model_address_upload.py
- api/registry/test/test_command_process_batch_address_upload.py
- infra/aws/index.ts
Fixes: https://github.com/passportxyz/passport/issues/2680
> 2680 increase instance

- api/ceramic_cache/api/schema.py
- api/ceramic_cache/api/v1.py
- api/ceramic_cache/test/test_authenticate_v1.py
- api/scorer/settings/base.py
fixes https://github.com/passportxyz/passport/issues/2780
> feat(api): add intercom user hash to auth response

- .github/workflows/build_and_deploy_review.yml
- api/registry/management/commands/process_batch_model_address_upload.py
- api/registry/test/test_command_process_batch_address_upload.py
- api/scorer/settings/base.py
- infra/aws/index.ts
- infra/lib/scorer/s3_initiated_ecs_task.ts
This fixes https://github.com/passportxyz/passport/issues/2795
> 2795 mbd batch targeted runs

- api/aws_lambdas/tests/test_with_api_request_exception_handling.py
- api/aws_lambdas/utils.py
- api/ceramic_cache/management/commands/base_cron_cmds.py
- api/passport/api.py
- api/passport/test/test_analysis.py
- api/registry/api/utils.py
- api/registry/management/commands/process_batch_model_address_upload.py
- api/registry/test/test_command_process_batch_address_upload.py
- api/registry/test/test_ratelimit.py
- api/scorer/api.py
- api/scorer/settings/base.py
Fixes: https://github.com/passportxyz/passport/issues/2937
> 2937 include link to rate limit form in rate limit error messages

- infra/aws/index.ts
This fixes https://github.com/passportxyz/passport/issues/3020
> adjust passport analysis response time alarm threshold

- infra/aws/index.ts
Fixes: https://github.com/passportxyz/core-infra/issues/57
> feat: remove troubleshooting instance

- api/v2/aws_lambdas/stamp_score_GET.py
Fixes: https://github.com/passportxyz/passport/issues/3093
> fix: rmeove import of numpy in v2 score handler

- api/aws_lambdas/submit_passport/Dockerfile
Fixes: https://github.com/passportxyz/passport/issues/3037
> 3037 embed route embed interactions through api endpoint 1

- api/embed/api.py
- api/embed/test/test_api_validate_api_key.py
Fixes: https://github.com/passportxyz/passport/issues/3294
> 3294 bug embed cant handle unlimited api keys

- api/v2/test/test_passport_submission.py
Fixes: https://github.com/passportxyz/passport/issues/3189
> fix: failing tests because of removed 'hash' attribute in Stamp

- api/registry/human_points_utils.py
- api/registry/test/test_human_points_api_response.py
- api/registry/test/test_human_points_models.py
Removes the multiplier from points calculation in the `get_user_points_data` function.
- Modified SQL query in `registry/human_points_utils.py` to use `SUM(hpc.points)` instead of `SUM(hpc.points * COALESCE(hpm.multiplier, 1))`
- Points breakdown now returns raw values without multiplication
- Total points calculation remains mathematically correct as sum of raw values
- Multiplier is still retrieved and returned for frontend reference
- Points data will now show raw values (e.g., CSB: 100 instead of 200 with 2x multiplier)
- Total points will be sum of raw values
- Multiplier field still available for frontend use
- Frontend will receive un-multiplied point values in breakdown
- No breaking changes to API structure
> fix: remove multiplier from points calculation in get_user_points_data
