passportxyz/passport-scorer

infra/prod/index.ts
=> fix(infra): protect db from deletition

infra/prod/index.ts
This adds autoscaling policy for the scoring service https://github.com/gitcoinco/passport/issues/833
=> feat(infra): adding autoscaling policy to scoring service

api/registry/api.py, api/registry/test/test_signing_message.py, examples/example-score-a-passport/index.html
This closes: https://github.com/gitcoinco/passport/issues/825
=> 825 scoring example with signature

Readme.md, api/registry/tasks.py, api/registry/test/test_passport_submission.py, api/scorer/test/features/submit_passport.feature, api/scorer/test/test_submit_passport.py
fixes(#871, #827): improve tests and fix minor bug
- adjust feature definitions and test cases for async passport submissions
- reset error when scoring is successful
Fixes:
https://github.com/gitcoinco/passport/issues/871
https://github.com/gitcoinco/passport/issues/827
=> fixes(#871, #827): improve tests and fix minor bug

CONTRIBUTING.md, Readme.md, SETUP.md, api/.env-sample
Implements #52, including
- Updates to the readme
- A setup guide
- A contributing guide
Also includes a small fix to the example `.env` file
=> 52 - Updates the readme and adds setup and contributing guides

api/Pipfile, api/Pipfile.lock, api/reader/passport_reader.py, api/reader/tests.py, api/registry/tasks.py
This fixes: https://github.com/gitcoinco/passport/issues/913
=> 885 score cached stamps

api/ceramic_cache/admin.py, api/ceramic_cache/api.py, api/ceramic_cache/test/test_get_stamps.py, api/ceramic_cache/test/test_submit_stamp.py, api/registry/test/test_score_passport.py, verifier/README.md
Get endpoint for https://github.com/gitcoinco/passport/issues/912
=> feat(api): add get endpoint for cached stamps

api/Pipfile, api/Pipfile.lock, api/scorer/pipeline.py, api/scorer/settings/base.py, api/scorer/templates/login.html, api/scorer/urls.py
fixes: https://github.com/gitcoinco/passport/issues/934
=> 934 google admin signin

api/registry/api.py, api/registry/exceptions.py, api/registry/management/commands/create_user_groups.py, api/registry/permissions.py, api/registry/test/test_passport_get_score.py, api/registry/utils.py, api/scorer/settings/env.py
closes https://github.com/gitcoinco/passport/issues/922
closes https://github.com/gitcoinco/passport/issues/923
closes https://github.com/gitcoinco/passport/issues/924
=> feat: researcher API access

api/account/admin.py, api/registry/api.py, api/registry/test/test_api_auth_required.py, api/registry/test/test_passport_get_score.py
This fixes: https://github.com/gitcoinco/passport/issues/960
=> feat: accept api key in 'X-API-Key' header for community API

.pre-commit-config.yaml, api/registry/api.py, api/registry/test/test_passport_get_score.py, api/scorer/api.py, api/scorer/urls.py
data analytics api docs -> `/analytics/docs`
closes https://github.com/gitcoinco/passport/issues/959
=> feat: show only public endpoints in docs

.pre-commit-config.yaml, api/ceramic_cache/api.py, api/ceramic_cache/exceptions.py, api/ceramic_cache/test/conftest.py, api/ceramic_cache/test/test_bulk_updates.py, api/scorer/settings/base.py, api/scorer/test/conftest.py
Fixes: https://github.com/gitcoinco/passport/issues/946
=> 946 implement bulk requests

api/registry/api.py, api/registry/exceptions.py, api/registry/test/test_passport_get_score.py, api/scorer/api.py
This fixes: https://github.com/gitcoinco/passport-scorer/issues/85
=> feat(api,docs): starting updates to the API docs

infra/review/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/984
=> 984 log retention

.github/ci-staging.yml, .github/workflows/ci-staging-interface.yml, .github/workflows/ci-staging.yml, infra/review/index.ts, infra/staging/.gitignore, infra/staging/Pulumi.staging.yaml, infra/staging/Pulumi.yaml, infra/staging/index.ts, infra/staging/package-lock.json, infra/staging/package.json, infra/staging/tsconfig.json
fixes: https://github.com/gitcoinco/passport/issues/970
=> 970 staging infra

api/Pipfile, api/Pipfile.lock, api/ceramic_cache/api.py, api/ceramic_cache/test/test_authenticate.py, api/ceramic_cache/test/test_utils.py, api/ceramic_cache/utils.py
Fixes: https://github.com/gitcoinco/passport/issues/952
This also depends on: https://github.com/gitcoinco/passport/pull/989
=> 952 verify payload on authenticate

.github/workflows/ci-staging.yml
should fix issue pushing image to verifier ECR
=> fix(infra): use staging environment for staging ci

.github/workflows/ci-staging.yml
Reverts gitcoinco/passport-scorer#113
=> Revert "fix(infra): move environment flag after runner"

interface/components/Footer.tsx, interface/components/Header.tsx, interface/pages/index.tsx
Consolidated some unnecessary divs, dialed in some margins, and made the main content flex-**grow** when in mobile view so that the content is at the top of the screen.
Per https://github.com/gitcoinco/passport/issues/971#issuecomment-1440238290
=> feature(interface): fine tuned spacing for home page

interface/pages/dashboard/new-scorer.tsx
closes https://github.com/gitcoinco/passport/issues/975
=> chore: finalize choose mechanism page copy

api/account/api.py, api/account/test/test_community.py, interface/__tests__/pages/tabRoute.scorer.test.tsx, interface/components/CommunityCard.tsx, interface/components/CommunityList.tsx, interface/components/CustomIcons.tsx, interface/utils/account-requests.ts
This fixes: https://github.com/gitcoinco/passport/issues/976
=> 976 scorer dashboard

infra/review/index.ts
move review deployment of the API to api.review.gitcoin.co
=> feat(api): move review deployment of the API to api.review.gitcoin.co

infra/staging/index.ts
This relates to: https://github.com/gitcoinco/passport/issues/1010
=> fix(infra,staging): fixing domain name for staging

interface/__tests__/context/userContext.test.tsx, interface/context/userContext.tsx
fixes: [1018](https://github.com/gitcoinco/passport/issues/1018)
=> fix(interface): log user out if they have two wallets connected

api/registry/api.py, examples/example-score-a-passport/index.html
This fixes: https://github.com/gitcoinco/passport/issues/1023
=> 1023 rename community

interface/__tests__/components/UseCaseModal.test.tsx, interface/components/CommunityList.tsx, interface/components/UseCaseModal.tsx
fixes: https://github.com/gitcoinco/passport/issues/1015
=> fix(interface): show duplicate name error within modal

api/registry/api.py, api/registry/test/test_passport_get_score.py
This fixes: https://github.com/gitcoinco/passport/issues/1030
Open points:
=> 1030 boost analytics api

api/registry/test/test_analytics_api_auth_required.py, api/registry/test/test_api_auth_required.py
Provides fixes: https://github.com/gitcoinco/passport/issues/1026
=> double-check security and authorization/authentication checks for API

interface/__tests__/components/NewScorer.test.tsx, interface/components/Dashboard.tsx, interface/components/Footer.tsx, interface/components/Header.tsx, interface/components/HeaderContentFooterGrid.tsx, interface/components/HomePageLayout.tsx, interface/components/MinimalHeader.tsx, interface/components/NewScorer.tsx, interface/components/PageLayout.tsx
Better react rendering, simpler. Prep for ui tweak ticket
=> pushed header/footer layout down to the individual top-level pages, 

interface/__test-fixtures__/userContextTestHelper.tsx, interface/__tests__/components/LandingPage.test.tsx, interface/components/LandingPage.tsx
fixes https://github.com/gitcoinco/passport/issues/1017
=> disable SIWE button while loading

api/registry/api.py, api/registry/test/test_passport_get_stamps.py, api/registry/utils.py
Adds a new endpoint to fetch stamps for a given passport address
closes https://github.com/gitcoinco/passport/issues/995
=> feat: add endpoint to get passport stamps

interface/components/LandingPage.tsx
This is for issue 1048.
Not sure how to link PRs to issues yet
=> updated landing page copy

api/registry/api.py, api/registry/exceptions.py, api/registry/test/test_passport_submission.py
fixes: https://github.com/gitcoinco/passport/issues/1061
=> fix(api): rename community id to scorer id for documentation

interface/components/Footer.tsx, interface/package.json
closes https://github.com/gitcoinco/passport/issues/860
=> feat: add git commit hash to footer

api/account/test/test_account.py, api/registry/test/test_passport_submission.py
fixes: https://github.com/gitcoinco/passport-scorer/issues/22
=> 22 test lowercase address

api/registry/test/test_passport_submission.py
Fixes: https://github.com/gitcoinco/passport-scorer/issues/36
=> 36 adds tests to check if existing stamp w/newer expiry date is updated in passport

api/registry/api.py, api/registry/api/base.py, api/registry/api/schema.py, api/registry/api/v1.py, api/registry/api/v2.py, api/registry/test/test_api_auth_required.py, api/registry/test/test_passport_get_score.py, api/registry/test/test_passport_get_stamps.py, api/registry/test/test_ratelimit.py, api/registry/test/test_score_passport.py, api/registry/utils.py, api/scorer/api.py, api/scorer/test/test_retrieving_multiple_scores.py, api/scorer/urls.py
This is to add my pagination changes to the get_scores endpoint
closes https://github.com/gitcoinco/passport/issues/1045
=> feat: add token pagination to get_scores endpoint

api/ceramic_cache/api.py
This fixes: https://github.com/gitcoinco/passport/issues/1178
=> fix(api): load account by the comunity id

infra/prod/index.ts, infra/staging/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/1189
=> feat(api): enable json logging to staging & production as well

infra/prod/index.ts
closes https://github.com/gitcoinco/passport/issues/1190
=> feat(infra): reduce cpu and increase maxCapacity

api/registry/api/v1.py, api/registry/test/test_passport_get_stamps.py
close https://github.com/gitcoinco/passport-scorer/issues/238
=> feat(api): read stamps from cache for registry api endpoint

api/.env-sample, api/registry/api/schema.py, api/registry/api/v1.py, api/registry/test/test_passport_get_stamps.py, api/scorer/settings/base.py, infra/prod/index.ts, infra/review/index.ts, infra/staging/index.ts
fixes https://github.com/gitcoinco/passport/issues/1235
=> 1235 stamp metadata

.github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml, .github/workflows/interface-promote-prod.yml, .github/workflows/interface-promote-staging.yml, .github/workflows/release_and_deploy_scorer.yml
fixes https://github.com/gitcoinco/passport/issues/1090
=> 1190 auto releases 1

infra/prod/index.ts
This reverts commit 44c47e563e2d312ded35a11fe90971d455a53f99.
Temporarily reverting changes for: https://github.com/gitcoinco/passport/issues/1330
=> Revert "bumping production db (#266)"

infra/prod/index.ts
This reverts commit 8149b8f1bcd15ff3f1ba39ebde5a2e2e0d3b7560.
This re-enable  the new DB instance settings for prod.
=> Revert "Revert "bumping production db (#266)" (#268)"

api/ceramic_cache/api.py, api/ceramic_cache/exceptions.py, api/ceramic_cache/test/test_bulk_updates.py, load_tests/script.js
fixes https://github.com/gitcoinco/passport/issues/1325
=> feat(api): added a PATCH ceramic-cache/stamps/bulk endpoint

api/account/deduplication/fifo.py, api/account/deduplication/lifo.py, api/account/models.py, api/registry/api/base.py, api/registry/api/v1.py, api/registry/exceptions.py, api/scorer_weighted/computation.py, api/scorer_weighted/models.py
This fixes: https://github.com/gitcoinco/passport/issues/1332
=> feat(api,async): WIP async implementation for

infra/staging/index.ts
This fixes:  https://github.com/gitcoinco/passport/issues/1329
=> fix(api,celery): creating separate workers for score calculation

api/Pipfile.lock, api/registry/api/base.py, api/registry/api/v1.py, api/registry/tasks.py
Fixes: https://github.com/gitcoinco/passport/issues/1332
This will fix the auth problem for the async version of submit-passport
=> fix(api,async): fixing the auth for the async

api/scorer/settings/gitcoin_passport_weights.py
closes [#1343](https://github.com/gitcoinco/passport/issues/1343)
=> fix(app): updating zksync 1.0 to lite

api/registry/api/v1.py
Show submit-passport endpoint in docs
=> fix(api): show submit passport in docs

infra/review/index.ts
fixes: https://github.com/gitcoinco/passport/issues/1309
=> fix(infra): add additional workers to review environment

api/registry/api/base.py, api/scorer/api.py, examples/example-score-a-passport/index.html
This fixes: https://github.com/gitcoinco/passport/issues/1332
- adds back the submit-passport request in the live docs
- updates the example according to our latest documentation
=> 1332 docs and examples

infra/prod/index.ts
Update read replica instance size to avoid timeouts. Fixes: #1350
=> fix(infra): update replica db instance type

api/passport_admin/api.py
=> fix(api): make link an optional parameter

api/account/deduplication/lifo.py, api/registry/admin.py
fixes https://github.com/gitcoinco/passport/issues/1515
=> fix(api): added admin for hash links, added error message

api/registry/api/schema.py, api/registry/api/v1.py, api/registry/exceptions.py, api/registry/test/test_passport_get_score.py
fixes: https://github.com/gitcoinco/passport/issues/1562
=> chore(api): sort scores by pk

api/scorer/settings/gitcoin_passport_weights.py
fixes: https://github.com/gitcoinco/passport/issues/1449
=> feat(api): add cyberconnect weights

api/registry/management/commands/propagate_weights_and_rescore.py, api/registry/test/test_propagate_weights_and_rescore.py
=> feat(api): conditionally rescore

api/scorer/settings/gitcoin_passport_weights.py
closes: https://github.com/gitcoinco/passport/issues/1559
=> chore(api): removes gitpoap weight

api/registry/management/commands/propagate_weights_and_rescore.py, api/registry/test/test_propagate_weights_and_rescore.py
=> fix(api): use flag as boolean

api/cgrants/api.py, api/cgrants/test/test_cgrants_api.py
fixes: https://github.com/gitcoinco/passport/issues/1507
=> feat(cgrants): only return contributions greater than 1 dollar

api/scorer/settings/gitcoin_passport_weights.py
https://github.com/gitcoinco/passport/issues/1507
=> feat(api): add grantsstack weights

.github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml, infra/prod/index.ts, infra/staging/index.ts
fixes: https://github.com/gitcoinco/passport-scorer/issues/315
Repo that is linked in startup script https://github.com/gitcoinco/passport-redash
=> chore(infra): setup redash instance within pulumi

infra/staging/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/1537
=> Refactor Scorer Service into Distinct Service Groups

api/ceramic_cache/management/commands/scorer_dump_data.py, infra/prod/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/1645
=> feat(api): adding generic script to create data dumps

.github/workflows/api-ci-review.yml
=> fix(infra): update review ci to account for updated infra

api/registry/api/v1.py
fixes: https://github.com/gitcoinco/passport/issues/1468
=> fix(api): properly type xStakeAggregate

infra/lib/scorer/scheduledTasks.ts, infra/prod/index.ts
This fixes errors that came up during deployment to prod today.
=> fix(infra): fixing task scheduling and definitions

.github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml, infra/prod/index.ts, infra/staging/index.ts
fixes issues with redash instance
=> Fix redash

infra/lib/scorer/scheduledTasks.ts, infra/lib/scorer/service.ts, infra/package-lock.json, infra/package.json, infra/prod/index.ts, infra/review/index.ts, infra/staging/index.ts
fixes https://github.com/gitcoinco/passport/issues/1650
=> refactor(infra): updating pulumi libraries

load_tests/README.md
=> fix(api,load_test): update readme

api/ceramic_cache/management/commands/scorer_dump_data.py, infra/lib/scorer/service.ts, infra/prod/index.ts
This fixes: https://github.com/gitcoinco/passport/issues/1677
=> fix(infra): change destination for public scores & config of cloudfront

api/trusta_labs/api.py, api/trusta_labs/test/test_trusta_labs_score.py
fixes https://github.com/gitcoinco/passport/issues/1629
=> feat(api): storing additional trustalabs score details

api/registry/api/common.py, api/registry/api/utils.py, api/registry/api/v1.py, api/registry/api/v2.py, api/registry/test/test_ratelimit.py, api/registry/test/test_v2_passport_get_score.py, api/scorer/api.py
fixes https://github.com/gitcoinco/passport/issues/1734
=> feat(api): switching back to v1 docs by default, backporting historical scores to v1

api/registry/api/schema.py, api/registry/management/commands/recalculate_scores.py, api/registry/test/conftest.py, api/registry/test/test_command_recalculate_scores.py, api/scorer/test/conftest.py, api/scorer_weighted/computation.py, api/scorer_weighted/models.py
This fixes: https://github.com/gitcoinco/passport/issues/1746
It introduces a django command that performs rescoring in batches.
=> 1746 rescoring command

.github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml, infra/prod/index.ts, infra/staging/index.ts
=> fix(infra): add TRUSTED_IAM_ISSUER to lambda env

api/registry/api/v1.py, api/registry/exceptions.py, api/registry/test/test_address_validation.py, api/scorer/test/test_choose_binary_scorer.py, api/scorer/test/test_submit_passport.py, infra/lib/scorer/service.ts
=> fix(api): check for invalid addresses, fixed 5xx alarm threshold

api/aws_lambdas/submit_passport/submit_passport.py, api/aws_lambdas/submit_passport/tests/test_submit_passport_lambda.py, api/registry/api/v1.py
Fixes: https://github.com/gitcoinco/passport-scorer/issues/424
=> fix(api): improving error handling, remove useless error logs

api/registry/api/v1.py, api/registry/api/v2.py
fixes: https://github.com/gitcoinco/passport/issues/1590
=> chore(api): validate address for remaining endpoints

indexer/src/main.rs, indexer/src/postgres.rs
fixes: (https://github.com/gitcoinco/passport/issues/1667)
=> fix(indexer): account for unused events and log errors

infra/prod/index.ts, infra/staging/index.ts
fixes https://github.com/gitcoinco/passport-scorer/issues/427
=> feat(infra): add redash email support

infra/lib/scorer/scheduledTasks.ts, infra/prod/index.ts, infra/staging/index.ts
https://github.com/gitcoinco/passport/issues/1735
=> feat(infra): added metrics and pagerduty alert for scheduled tasks

infra/lib/scorer/service.ts, infra/prod/index.ts, infra/staging/index.ts
Fixies: https://github.com/gitcoinco/passport/issues/1869
=> fix(infra): creating an indexer instance in staging

indexer/Cargo.lock, indexer/Cargo.toml, indexer/src/main.rs, indexer/src/postgres.rs, infra/lib/scorer/service.ts, infra/prod/index.ts, infra/staging/index.ts
Fixes connection issues in indexer
=> chore(indexer, infra): use deadpool to manage rds proxy connections

indexer/Cargo.lock, indexer/Cargo.toml, indexer/src/main.rs, indexer/src/postgres.rs
Fixes: https://github.com/gitcoinco/passport/issues/1915
=> 1915 connection issues

infra/.gitignore, infra/lib/scorer/service.ts, infra/prod/index.ts, infra/staging/index.ts
fixes: https://github.com/gitcoinco/passport-scorer/issues/449
=> feat(infra): downsizes ecs resources

infra/lib/scorer/service.ts, infra/prod/index.ts
fixes: https://github.com/gitcoinco/passport-scorer/issues/449
=> infra: downsizing of ECS tasks in prod

api/registry/api/common.py, api/registry/api/v1.py, api/registry/api/v2.py, api/scorer/api.py
fixes: https://github.com/gitcoinco/passport/issues/1716
=> chore(api): updates swagger UI with new descriptions/summaries

.github/workflows/api-ci-review.yml, .github/workflows/api-promote-staging.yml, .github/workflows/ci.yml, api/aws_lambdas/Readme.md, api/aws_lambdas/utils.py, api/scorer/settings/base.py, infra/lib/scorer/service.ts, infra/prod/index.ts, infra/staging/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/1941
=> 1941 lambda load ssm

api/aws_lambdas/utils.py
fixes: https://github.com/gitcoinco/passport/issues/1941 and https://github.com/gitcoinco/passport-scorer/actions/runs/6982521105/job/19001836438
=> fix(api): don't run load_secrets in tests

indexer/.env.example, indexer/Cargo.lock, indexer/src/main.rs, indexer/src/postgres.rs, infra/lib/scorer/service.ts
fixes https://github.com/gitcoinco/passport/issues/1974
=> feat(indexer): adding reconnect logic

interface/package.json, interface/utils/onboard.ts, interface/yarn.lock
fixes https://github.com/gitcoinco/passport/issues/1982
=> fix(app): temporarily removing walletconnect due to ledger issue

interface/utils/onboard.ts
Fixes: https://github.com/gitcoinco/passport/issues/1983
=> chore(app): re enable wallet connect

api/cgrants/admin.py, api/cgrants/models.py
fixes: https://github.com/gitcoinco/passport/issues/1931
=> chore(api): make squelched accounts visible in admin

infra/lib/scorer/service.ts
fixes https://github.com/gitcoinco/passport/issues/1995
=> fix(infra): fix queue lambda permissions

api/cgrants/management/commands/import_squelched_users.py
fixes: https://github.com/gitcoinco/passport/issues/2025
=> fix(api): update round number on import

api/scorer/settings/gitcoin_passport_weights.py
Fixes: https://github.com/gitcoinco/passport/issues/2027
=> chore(api): update weights for new ETH stamp

api/scorer/settings/gitcoin_passport_weights.py
Fixes: [#2075](https://github.com/gitcoinco/passport/issues/2075)
=> chore(api): update weights

infra/prod/index.ts, infra/staging/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2081
=> fix[infra]: install docker-compose in redash instances

infra/prod/index.ts, infra/staging/index.ts
Fixing: https://github.com/gitcoinco/passport/issues/2081
=> 2081 redash install docker 1

api/aws_lambdas/submit_passport/submit_passport.py
fixes: https://github.com/gitcoinco/passport/issues/2126
=> fix(api): store path for lambda

api/ceramic_cache/models.py, api/ceramic_cache/test/test_db_data_model.py, infra/prod/index.ts, infra/staging/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2110
=> 2110 intermediate migration 2

infra/prod/index.ts, infra/staging/index.ts
- install postgresql-client-13 client on troubleshooting instance
- drop installation of docker-compose in redash (this will be installed from the setup.sh script)
- add 'Name' tag to the ec2 instances
fixes: https://github.com/gitcoinco/passport/issues/2081
=> fix[infra]: update ec2 instance

infra/prod/index.ts, infra/staging/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2139
=> feat[infra]: adjust DBs for prod and remove analytics db for staging

.github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml
Fixes: https://github.com/gitcoinco/passport/issues/2140
=> fix[infra]: fix dependencies of jobs in release workflows

api/aws_lambdas/utils.py
Fixes: https://github.com/gitcoinco/passport/issues/2140
=> fix[api]: fix import order

api/registry/atasks.py, api/registry/tasks.py
Fixes: https://github.com/gitcoinco/passport/issues/2140
=> feat[api]: stripping headers from sensitive data

api/registry/atasks.py
Fixes: https://github.com/gitcoinco/passport/issues/2140
=> 2140 enhanced logging 7

api/registry/management/commands/deduplication_export.py
fixes https://github.com/gitcoinco/passport/issues/2181
=> fix: including original address in list of addresses involved in deduplication

infra/prod/index.ts
=> fix(infra): fixed redash emails

api/ceramic_cache/management/commands/scorer_dump_data.py, api/ceramic_cache/test/test_cmd_scorer_dump_data.py, infra/prod/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2209
=> 2209 fix scorer dump data 1

.github/workflows/api-ci-review.yml
This is required until https://github.com/gitcoinco/passport/issues/2007 is completed
=> Disable review

infra/prod/index.ts
This is required for cost reduction
=> downgrade database

api/aws_lambdas/passport/analysis_GET.py, api/aws_lambdas/passport/tests/conftest.py, api/aws_lambdas/passport/tests/test_passport_analysis_lambda.py, api/aws_lambdas/scorer_api_passport/v1/stamp_GET.py, api/aws_lambdas/tests/test_rescore_lambda.py, api/aws_lambdas/utils.py, api/passport/api.py, api/passport/test/test_analysis.py, api/passport/urls.py, api/registry/api/schema.py, api/registry/api/utils.py, api/registry/api/v1.py, api/registry/utils.py, api/scorer/api.py, api/scorer/urls.py, infra/aws/index.ts, infra/prod/index.ts, infra/staging/index.ts
fixes: https://github.com/gitcoinco/passport/issues/2034
=> feat(api): public eth model stamp

indexer/Dockerfile
fixes https://github.com/gitcoinco/passport/issues/2259
=> feat(infra): update rust version for indexer docker image

infra/lib/scorer/new_service.ts
fixes https://github.com/gitcoinco/passport/issues/2259
=> fix(infra): adding env vars to new infra file

infra/lib/scorer/scheduledTasks.ts
This should reset the alarm state in pulumi.
=> fix[infra]: adding  to alarms in scheduled tasks

.github/workflows/api-ci-review.yml, .github/workflows/api-promote-prod.yml, .github/workflows/api-promote-staging.yml, .github/workflows/ci.yml
Fixes: https://github.com/gitcoinco/passport/issues/2334
This adds new env variables required for the db connection for `data_model` app
=> feat(ci,workflow): add DATA_MODEL_DATABASE_URL env var for unit tests

infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2334
=> fix(api,infra): rename task role for ECS tasks

infra/aws/index.ts, infra/lib/scorer/scheduledTasks.ts
Fixes: https://github.com/gitcoinco/passport/issues/2334
=> fix(infra): specify task role for farget scheduled tasks

api/passport/api.py
Fixes: https://github.com/gitcoinco/passport/issues/2331
=> feat: switch the analysis API to the eth-stamp-v2-api

infra/aws/index.ts
Those changes were (partially) made manually in AWS . This fixes https://github.com/gitcoinco/passport/issues/2427
=> update data dump jobs (use read replica & set batch size)

infra/lib/scorer/new_service.ts, infra/lib/scorer/service.ts
fixes https://github.com/gitcoinco/passport/issues/2382
=> fix(infra): passing through new indexer env vars

api/data_model/management/commands/scorer_dump_data_model_score.py, api/data_model/test/test_cmd_scorer_dump_data_eth_model_score.py, infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2443
=> feat(api): wip - fix export of data model scores

infra/aws/index.ts, infra/lib/scorer/loadBalancer.ts, infra/lib/scorer/new_service.ts
Fixes: https://github.com/gitcoinco/passport/issues/2228
=> feat(infra): tweaking alarms

api/data_model/admin.py, api/data_model/models.py
Fixes: https://github.com/gitcoinco/passport/issues/2451
=> feat(api): updating data_model/models.py, key was removed

api/aws_lambdas/scorer_api_passport/tests/test_bulk_stamp_lambdas.py, api/aws_lambdas/scorer_api_passport/v1/stamps/bulk_DELETE.py, api/aws_lambdas/scorer_api_passport/v1/stamps/bulk_PATCH.py, api/aws_lambdas/scorer_api_passport/v1/stamps/bulk_POST.py, api/aws_lambdas/utils.py
This fixes https://github.com/gitcoinco/passport/issues/2464
=> reset db connection for bulk lambdas & improve error logging

.github/workflows/api-ci-review.yml
Fixes: https://github.com/gitcoinco/passport/issues/2464
=> fix: running unittests for backend in api-ci-review.yml

api/stake/api.py, api/stake/schema.py
Fixes: https://github.com/gitcoinco/passport/issues/2500
=> feat: /stake/gtc now also returns

infra/aws/index.ts
This fixes : https://github.com/gitcoinco/passport/issues/2545
=> (infra): use analytics read replica for data dumps jobs

infra/aws/index.ts, infra/lib/scorer/scheduledTasks.ts
This fixes https://github.com/gitcoinco/passport/issues/2545
=> Data dump apps

infra/aws/index.ts
This fixes https://github.com/gitcoinco/passport/issues/2574
=> include stake app for daily data dump

api/cgrants/management/commands/import_squelched_users.py
Fixes: https://github.com/gitcoinco/passport/issues/2561
=> fix: import of round data

api/aws_lambdas/passport/analysis_GET.py, api/passport/api.py, api/passport_admin/models.py
Fixes: https://github.com/gitcoinco/passport/issues/2459
=> draft: implementation of analysis endpoint o pull from multiple models

api/passport_admin/admin.py, api/passport_admin/notification_generators/expired_stamp.py
This fixes https://github.com/gitcoinco/passport/issues/2715  
This fixes https://github.com/gitcoinco/passport/issues/2716
=> update the expired stamp notification generators

.github/workflows/release_and_deploy_production.yml
Fixes: https://github.com/gitcoinco/passport/issues/2682
=> fix: push app code to branch in release workflow

api/data_model/management/commands/scorer_dump_data_model_score.py, api/data_model/test/test_cmd_scorer_dump_data_eth_model_score.py, infra/aws/index.ts
Fixes: https://github.com/gitcoinco/passport/issues/2720
=> feat: extended the export command to include the scores for all models

api/aws_lambdas/passport/tests/test_passport_analysis_lambda.py, api/passport/api.py, api/passport/test/test_analysis.py, api/scorer/settings/model_config.py
fixes https://github.com/passportxyz/passport/issues/2738
=> feat(api): refactor aggregate model to efficiently work when multiple models requested

.github/workflows/release_and_deploy_production.yml
Fixes:  https://github.com/passportxyz/passport/issues/2747
=> Jws verifier service 1

.github/workflows/release_and_deploy_production.yml
Fixes: https://github.com/passportxyz/passport/issues/2747
=> fix: add proper permissions to the steps pushing branches

api/passport/api.py
Fixes https://github.com/passportxyz/passport/issues/2680
=> fix: float first_funder

.github/workflows/build_and_deploy_generic.yml, .github/workflows/deploy_generic.yml
fixes https://github.com/passportxyz/passport/issues/2808
=> feat(infra): updating pulumi org name

api/account/models.py
fixes https://github.com/passportxyz/passport/issues/2785
=> fix(api): fix async issue for customization weights

api/account/models.py
Fixes: https://github.com/passportxyz/passport/issues/2820
=> feat: adding validation for inputs of IncludedChainId

api/scorer/pipeline.py
fixes: https://github.com/passportxyz/passport/issues/2809
=> chore: update to passportxyz gmail login

.github/workflows/build_and_deploy_generic.yml
Fixes: https://github.com/passportxyz/passport/issues/2845
=> feat(infra): add cloudflare token

infra/aws/index.ts
Fixes: https://github.com/passportxyz/passport/issues/2845
=> fix: deploy branches

api/ceramic_cache/management/commands/scorer_dump_data.py, api/data_model/management/commands/scorer_dump_data_model_score.py, infra/aws/index.ts, infra/lib/scorer/new_service.ts
This fixes https://github.com/passportxyz/passport/issues/2863
=> update cloudfront caching & add invalidation after upload

api/ceramic_cache/api/v1.py, api/registry/management/commands/get_unmonitored_urls_config.py, infra/yarn.lock
fixes https://github.com/passportxyz/passport/issues/2911
=> fix(iam): adding token-auth score endpoint

api/ceramic_cache/api/v1.py, infra/aws/index.ts
fixes https://github.com/passportxyz/passport/issues/2911
=> chore(api): updating path for score lambda

api/data_model/management/commands/scorer_dump_data_model_score.py
fixes https://github.com/passportxyz/passport/issues/2863
=> fix data model export

api/data_model/management/commands/scorer_dump_data_model_score.py
fixes https://github.com/passportxyz/passport/issues/2863
=> Fix data export

api/ceramic_cache/management/commands/scorer_dump_data.py, api/data_model/management/commands/scorer_dump_data_model_score.py, infra/aws/index.ts
fixes https://github.com/passportxyz/passport/issues/2863
=> add cloudfront permissions

api/ceramic_cache/management/commands/scorer_dump_data.py, api/data_model/management/commands/scorer_dump_data_model_score.py
This fixes https://github.com/passportxyz/passport/issues/2863
=> fix invalidation parameters

infra/aws/index.ts, infra/package.json, infra/yarn.lock
this fixes https://github.com/passportxyz/passport/issues/2916
=> add additional prefix developer

api/aws_lambdas/passport/tests/test_passport_analysis_lambda.py, api/passport/api.py, api/passport/test/test_analysis.py
Fixes: https://github.com/passportxyz/passport/issues/2849
=> fix: catch error reported by MDB API forward it to the caller

api/aws_lambdas/passport/tests/test_passport_analysis_lambda.py, api/aws_lambdas/submit_passport/tests/test_submit_passport_lambda.py, api/aws_lambdas/tests/test_with_api_request_exception_handling.py, api/ceramic_cache/test/test_authenticate_v1.py, api/ceramic_cache/test/test_cmd_scorer_dump_data.py, api/registry/test/test_passport_get_score.py, api/registry/test/test_passport_get_stamps.py
Fixes: https://github.com/passportxyz/passport/issues/2984
=> Fix pytest warnings

api/registry/api/v1.py
Fixes: https://github.com/passportxyz/passport/issues/2957
=> 2957 deprecation

api/data_model/management/commands/scorer_dump_data_model_score.py, infra/aws/index.ts, infra/lib/scorer/scheduledTasks.ts
This fixes https://github.com/passportxyz/passport/issues/2904
=> feat(infra): WIP data exports to grants account

api/ceramic_cache/management/commands/scorer_dump_data.py, api/data_model/management/commands/scorer_dump_data_model_score.py, api/data_model/test/test_cmd_scorer_dump_data_eth_model_score.py, infra/aws/index.ts
This fixes https://github.com/passportxyz/passport/issues/2904
=> add endpoint for data exports

infra/aws/index.ts
this fixes https://github.com/passportxyz/passport/issues/2904
=> Update grants data exports

infra/aws/index.ts
this fixes https://github.com/passportxyz/passport/issues/2904
=> fix credentials for data export

api/aws_lambdas/utils.py, api/registry/management/commands/get_unmonitored_urls_config.py, api/v2/api_stamps.py, api/v2/aws_lambdas/stamp_score_GET.py, api/v2/aws_lambdas/tests/conftest.py, api/v2/aws_lambdas/tests/test_stamp_score_get.py, api/v2/schema.py, api/v2/test/test_passport_submission.py, infra/aws/index.ts, infra/lib/scorer/new_service.ts
fixes https://github.com/passportxyz/passport/issues/2933
=> feat(api): updating schema for v2 score endpoint

infra/lib/v2/index.ts
Fix: https://github.com/passportxyz/passport/issues/2992
=> fix: errors in pulumi script

api/ceramic_cache/api/v1.py
Fixes: https://github.com/passportxyz/passport/issues/2992
=> fix: return type in weights request

api/ceramic_cache/test/test_weights.py
Fixes: https://github.com/passportxyz/passport-scorer/actions/runs/11519300859/job/32067977080
=> fix: weight return type

infra/aws/index.ts, infra/package.json, infra/yarn.lock
Fixes: https://github.com/passportxyz/passport/issues/3010
=> fix: adding somain api.passport.xyz + certificate

infra/aws/index.ts
Fixes: error caused by new passport app domain
=> fix(infra): base url for metadata call

api/aws_lambdas/submit_passport/tests/test_submit_passport_lambda.py, api/registry/api/schema.py
Fixes: https://github.com/passportxyz/passport/issues/3019#issue-2630759432
=> fix: handling numeric scorer_id in submit-passport

api/passport_admin/api.py, api/passport_admin/tests/test_notifications.py
Fixes: https://github.com/passportxyz/passport/issues/3000
=> feat: delete all endpoint

infra/aws/index.ts, infra/lib/scorer/loadBalancer.ts
Fixes: https://github.com/passportxyz/core-infra/issues/64
=> feat: updating alarm settings for cc-v1-st-bulk-DELETE-0

infra/aws/index.ts, infra/lib/scorer/new_service.ts, infra/lib/scorer/scheduledTasks.ts, infra/package.json, infra/yarn.lock
Fixes: https://github.com/passportxyz/core-infra/issues/39
=> feat: reworking ecs tasks to use aws

api/v2/api/__init__.py, api/v2/api/api_stamps.py
Fixes: https://discord.com/channels/1201910237238399006/1288497293083017236/1306706367188304014
=> chore(docs): update descriptions and summaries for open api spec

.github/workflows/ci.yml, .github/workflows/test_generic.yml, api/registry/management/commands/get_unmonitored_urls.py, api/registry/management/commands/get_unmonitored_urls_config.py, api/scorer/api.py, api/scorer/urls.py, api/v2/api/__init__.py
Fixes: https://github.com/passportxyz/passport/issues/3023
=> 3023 monitoring

api/v2/api/api_stamps.py, api/v2/test/test_historical_score_endpoint.py, infra/lib/v2/index.ts
Fixes: https://github.com/passportxyz/passport/issues/3062
Fixes: https://github.com/passportxyz/passport/issues/3065
=> 3062 historical endpoint fix

verifier/package.json, verifier/yarn.lock
fixes https://github.com/passportxyz/passport/issues/3014
=> chore(verifier): updating did packages

.github/workflows/ci.yml, .github/workflows/test_generic.yml, api/registry/management/commands/get_unmonitored_urls_config.py, api/registry/utils.py, api/v2/api/__init__.py, api/v2/api/api_stamps.py, api/v2/aws_lambdas/stamp_score_GET.py, api/v2/aws_lambdas/tests/test_stamp_score_get.py, api/v2/exceptions.py, api/v2/schema.py, api/v2/test/test_historical_score_endpoint.py, api/v2/test/test_passport_submission.py, infra/aws/index.ts, infra/lib/scorer/loadBalancer.ts
Fixes: https://github.com/passportxyz/passport/issues/3074#issue-2678595754
=> fix: remove '=' padding in pagination token

api/v2/aws_lambdas/stamp_score_GET.py
This fixes https://github.com/passportxyz/passport/issues/3003
=> remove unused import

api/ceramic_cache/admin.py, api/scorer/settings/storages.py
Fixes: https://github.com/passportxyz/passport/issues/3132
=> fix: use 'utf-8-sig' when uploading csv files for ban / revocation lists

infra/aws/index.ts
this fixes https://github.com/passportxyz/passport/issues/3131
=>  update grants file upload

infra/aws/index.ts
=> update ecs task data dump

.github/workflows/deploy_generic.yml, infra/aws/index.ts, infra/lib/scorer/loadBalancer.ts, infra/lib/scorer/new_service.ts, infra/lib/scorer/scheduledTasks.ts
fixes https://github.com/passportxyz/passport/issues/3108
=> chore(infra): adding burst/sustain AWS alarms, adjusting alarms

infra/aws/index.ts, infra/lib/scorer/new_service.ts
This fixes https://github.com/passportxyz/passport/issues/3106
=> replace public scorer record

infra/aws/index.ts, infra/lib/scorer/new_service.ts
This fixes https://github.com/passportxyz/passport/issues/3106
=> Fix public record

infra/aws/index.ts
This fixes https://github.com/passportxyz/passport/issues/3151
=> Rds db v16 2

api/ceramic_cache/management/commands/backfill_shape_scores.py, api/registry/management/commands/compare_shape_scores.py
fixes https://github.com/passportxyz/passport/issues/3161
=> chore: script for backfilling shape scores

api/ceramic_cache/api/v1.py, infra/aws/index.ts, infra/lib/scorer/s3_initiated_ecs_task.ts, infra/lib/scorer/scheduledTasks.ts
fixes https://github.com/passportxyz/passport/issues/3162
=> fix: fixed issue with batch rescoring s3 trigger and bug in internal score endpoint

infra/aws/embed/lambda_generic.ts, infra/aws/embed/rate_limit.ts
fixes https://github.com/passportxyz/passport/issues/3169
=> chore(api): increasing memory for embed lambdas

api/embed/api.py, api/embed/test/test_api_weights.py
This fixes https://github.com/passportxyz/passport/issues/3205
=> feat(embed): add a new embed api endpoint for weights

api/aws_lambdas/submit_passport/tests/test_submit_passport_lambda.py, api/aws_lambdas/utils.py, api/v2/aws_lambdas/tests/test_stamp_score_get.py
fixes https://github.com/passportxyz/passport/issues/3225
=> feat(api): keep API key prefix in event info

infra/aws/app_api/lambda_generic.ts
Fixes: https://github.com/passportxyz/passport/issues/3273
=> fix: forgot to add infra file

api/app_api/lambda_fn.py
Fixes: https://github.com/passportxyz/passport/issues/3273
=> fix: import order of packages in lambda module

infra/aws/index.ts
This fixes https://github.com/passportxyz/passport/issues/3280
=> feat(infra): fix infra error

api/scorer/pipeline.py
Fixes: https://github.com/passportxyz/passport/issues/3319
=> 3319 change sign in for django admin

api/embed/api.py, api/internal/api.py, api/v2/api/api_stamps.py, api/v2/aws_lambdas/stamp_score_GET.py, api/v2/test/test_passport_submission.py
fixes https://github.com/passportxyz/passport/issues/3189
=> feat(api): adding v2 score endpoint to internal API

api/account/admin.py
this fixes https://github.com/passportxyz/passport/issues/3279
=> feat(waf): treat 1 api key case

.github/workflows/deploy_generic.yml
this fixes https://github.com/passportxyz/passport/issues/3279
=> feat(workflow): ensure poetry is installed for pulumi up

api/account/api.py, api/ceramic_cache/api/v1.py, api/cgrants/api.py, api/embed/api.py, api/embed/test/test_api_validate_api_key.py, api/internal/test/test_allow_list.py, api/scorer/urls.py, api/stake/api.py
fixes https://github.com/passportxyz/passport/issues/3321
=> chore(api): removing old versions of relocated endpoints

.github/workflows/ci.yml, api/account/admin.py
this fixes https://github.com/passportxyz/passport/issues/3279
=> feat(waf): convert tier 1 rate limiting as default rules

api/account/admin.py
this fixes https://github.com/passportxyz/passport/issues/3353
=> update waf error message

.github/workflows/build_and_deploy_generic.yml, api/aws_lambdas/scorer_api_passport/tests/test_bulk_stamp_lambdas.py, api/aws_lambdas/scorer_api_passport/v1/stamps/bulk_POST.py, api/aws_lambdas/utils.py, system_tests/src/tests/iam.test.ts
Fixes: https://github.com/passportxyz/passport/issues/3172
=> 3172 monitoring regular run monitoring of the system tests 4

api/account/admin.py
this fixes https://github.com/passportxyz/passport/issues/3354
=> feat(waf): add waf labels

.github/workflows/build_and_deploy_generic.yml, .github/workflows/deploy_generic.yml
this fixes https://github.com/passportxyz/passport/issues/3323
=> modify source secret for aws credentials

api/account/admin.py
Fixes: https://github.com/passportxyz/core-infra/issues/68
=> feat: changing priorities of generated waf rules

.github/workflows/build_and_deploy_generic.yml
pass on session_token to build_and_push action
=> feat: pass on session_token to build_and_push action

infra/scripts/ops/lambda_call.py
this fixes https://github.com/passportxyz/passport/issues/3323
=> use session token if needed

.github/workflows/sync_to_s3_generic_app.yml, infra/aws/index.ts
Fixes:  https://github.com/passportxyz/core-infra/issues/106
=> Fix op command

.github/workflows/build_and_deploy_generic.yml, .github/workflows/deploy_generic.yml, .github/workflows/interface-ci-production.yml, .github/workflows/interface-ci-review.yml, .github/workflows/interface-ci-staging.yml, .github/workflows/release_and_deploy_production.yml, .github/workflows/sync_to_s3_generic_app.yml, .github/workflows/sync_to_s3_generic_build_app.yml, .github/workflows/sync_to_s3_generic_push_app.yml
Fixes:  https://github.com/passportxyz/passport/issues/3371
=> fix: credentials for aws missing when pushing to s3

system_tests/.env.example, system_tests/jest/setupAfterEnv.js, system_tests/src/tests/account_ui.test.ts, system_tests/src/tests/iam.test.ts, system_tests/src/tests/internal_api.test.ts, system_tests/src/tests/setup.test.ts, system_tests/src/users/PassportUIUser.ts
fixes https://github.com/passportxyz/passport/issues/3384
=> feat(systests): adding account UI tests, more internal tests, request logging

.github/workflows/build_and_deploy_generic.yml, .github/workflows/sync_to_s3_generic_build_app.yml, .github/workflows/sync_to_s3_generic_push_app.yml
Fixes: https://github.com/passportxyz/passport/issues/3371
=> feat: adding env to app build artifact name

infra/aws/index.ts, infra/yarn.lock
Fixes: https://github.com/passportxyz/passport/issues/3371
=> feat: drop amplify

.github/workflows/sync_to_s3_generic_build_app.yml, .github/workflows/sync_to_s3_generic_push_app.yml
Fixes: https://github.com/passportxyz/passport/issues/3395
=> feat: fix building of app

.github/workflows/build_and_deploy_generic.yml, .github/workflows/build_and_deploy_production.yml, .github/workflows/build_and_deploy_review.yml, .github/workflows/build_and_deploy_staging.yml, .github/workflows/deploy_app_generic.yml, .github/workflows/deploy_generic.yml, .github/workflows/deploy_production.yml, .github/workflows/deploy_review.yml, .github/workflows/deploy_staging.yml, .github/workflows/release_and_deploy_production.yml, .github/workflows/sync_to_s3_generic_push_app.yml, infra/aws/index.ts
Fixes: https://github.com/passportxyz/passport/issues/3395
=> feat: update workflows to use gh-workflows v3

.github/workflows/infra.yml
this fixes https://github.com/passportxyz/passport/issues/3309
=> fix infra deployment

api/registry/atasks.py
fixes https://github.com/passportxyz/passport/issues/3141
=> chore(api): removing override now that old credentials expired

api/scorer/settings/model_config.py
fixes https://github.com/passportxyz/passport/issues/3368
=> feat(api): adding base model

infra/aws/index.ts, infra/aws/v2/index.ts, infra/lib/scorer/loadBalancer.ts, infra/lib/scorer/new_service.ts
this fixes https://github.com/passportxyz/passport/issues/3414 
this fixes https://github.com/passportxyz/passport/issues/3415
=> feat(infra): increase ALB timeout, drop 4xx error

system_tests/index.mjs, system_tests/jest-runner.mjs, system_tests/jest/DBLoggerReporter.js, system_tests/jest/setupAfterEnv.js, system_tests/src/global.d.ts, system_tests/src/utils/testRequest.ts
fixes https://github.com/passportxyz/passport/issues/3428
=> fix(sys-tests): fixed bug with jest cleanup in system test lambda

.github/workflows/build_and_deploy_generic.yml, .github/workflows/deploy_generic.yml, .github/workflows/infra.yml, .github/workflows/sync_to_s3_generic_push_app.yml
this fixes https://github.com/passportxyz/passport/issues/3431
=> update session token load

infra/aws/index.ts, infra/aws/verifier.ts, infra/lib/scorer/new_service.ts, infra/lib/scorer/scheduledTasks.ts
this fixes https://github.com/passportxyz/passport/issues/3417
this fixes https://github.com/passportxyz/core-infra/issues/150
=> update logs retention period

api/passport/api.py, api/passport/test/test_analysis.py, api/scorer/settings/model_config.py
Fixes: https://github.com/passportxyz/passport/issues/3436
=> feat: adding the base model to the MODEL_AGGREGATION_NAMES

.hooks/lint_infra.sh, .hooks/lint_system_tests.sh, .pre-commit-config.yaml, api/aws_lambdas/exceptions.py, api/aws_lambdas/tests/test_with_api_request_exception_handling.py, api/embed/api.py, api/embed/lambda_fn.py, api/embed/test/test_api_get_score.py, api/embed/test/test_api_stamps.py, api/embed/test/test_lambda_get_score.py, api/internal/api.py, infra/aws/embed/index.ts, infra/aws/index.ts
Fixes: https://github.com/passportxyz/passport/issues/3439
=> feat: add lambda for getting score + adding unittests

system_tests/src/tests/internal_api.test.ts
fixes https://github.com/passportxyz/passport/issues/3443
=> fix(systests): updating expected rate limit response

api/account/api.py, api/registry/test/test_ratelimit.py
Fix: https://github.com/passportxyz/passport/issues/3480
=> fix: errors in API for dev portal

system_tests/jest/setupAfterEnv.js
fixes https://github.com/passportxyz/passport/issues/3475
=> feat(systests): adding automated retries

api/internal/api.py, api/internal/test/test_score_v2_endpoint.py, api/registry/atasks.py, api/registry/models.py, api/scorer/test/test_submit_passport.py, api/v2/api/api_stamps.py
fixes https://github.com/passportxyz/passport/issues/3490
=> fix(api): return error response on failed score for internal API

.hooks/lint_interface.sh, .pre-commit-config.yaml, infra/aws/index.ts, system_tests/src/tests/iam.test.ts
Fixes: https://github.com/passportxyz/passport/issues/3510
=> feat: update monioring metric for response time

api/registry/admin.py, api/registry/management/commands/process_batch_model_address_upload.py, api/v2/test/test_command_process_batch_address_upload.py, infra/aws/index.ts, infra/lib/scorer/s3_initiated_ecs_task.ts
Fixes: https://github.com/passportxyz/passport/issues/3513
=> fix: adding back previously commented tests

api/aws_lambdas/scorer_api_passport/tests/test_bulk_stamp_lambdas.py, api/aws_lambdas/scorer_api_passport/tests/test_stamp_lambdas.py, api/ceramic_cache/api/schema.py, api/ceramic_cache/api/v1.py, api/ceramic_cache/test/test_bulk_updates_v1.py, api/ceramic_cache/test/test_get_score.py, api/internal/api.py, api/v2/api/api_stamps.py
fixes https://github.com/passportxyz/passport/issues/3063
=> feat(api): using v2 score response for ceramic cache API

api/account/api.py
Fixes: https://github.com/passportxyz/passport/issues/3560
=> feat: add threshold to customisation api response

api/ceramic_cache/api/v1.py, api/registry/human_points_utils.py, api/v2/api/api_stamps.py
=> fix: include the user's multiplier when calculating their possible HUMN points
